<a href="https://colab.research.google.com/github/Dshreekulkarni/MATH189-FinalProject/blob/laleh/work.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [53]:
import pandas as pd

In [54]:
file_2015 = pd.read_csv('ACSDT1Y2015.B08301-Data.csv')
file_2016 = pd.read_csv('ACSDT1Y2015.B08301-Data.csv')
file_2017 = pd.read_csv('ACSDT1Y2015.B08301-Data.csv')
file_2018 = pd.read_csv('ACSDT1Y2015.B08301-Data.csv')
file_2019 = pd.read_csv('ACSDT1Y2015.B08301-Data.csv')
file_2021 = pd.read_csv('ACSDT1Y2015.B08301-Data.csv')
file_2022 = pd.read_csv('ACSDT1Y2015.B08301-Data.csv')
file_2023 = pd.read_csv('ACSDT1Y2015.B08301-Data.csv')
file_2024 = pd.read_csv('ACSDT1Y2015.B08301-Data.csv')

In [55]:
file_2015

,GEO_ID,NAME,B08301_001E,B08301_001M,B08301_002E,B08301_002M,B08301_003E,B08301_003M,B08301_004E,B08301_004M,...,B08301_017M,B08301_018E,B08301_018M,B08301_019E,B08301_019M,B08301_020E,B08301_020M,B08301_021E,B08301_021M,Unnamed: 44
0,Geography,Geographic Area Name,Estimate!!Total,Margin of Error!!Total,"Estimate!!Total!!Car, truck, or van","Margin of Error!!Total!!Car, truck, or van","Estimate!!Total!!Car, truck, or van!!Drove alone","Margin of Error!!Total!!Car, truck, or van!!Dr...","Estimate!!Total!!Car, truck, or van!!Carpooled","Margin of Error!!Total!!Car, truck, or van!!Ca...",...,Margin of Error!!Total!!Motorcycle,Estimate!!Total!!Bicycle,Margin of Error!!Total!!Bicycle,Estimate!!Total!!Walked,Margin of Error!!Total!!Walked,Estimate!!Total!!Other means,Margin of Error!!Total!!Other means,Estimate!!Total!!Worked at home,Margin of Error!!Total!!Worked at home,NaN
1,0500000US01003,"Baldwin County, Alabama",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,0500000US01015,"Calhoun County, Alabama",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,0500000US01043,"Cullman County, Alabama",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,0500000US01049,"DeKalb County, Alabama",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
826,0500000US72113,"Ponce Municipio, Puerto Rico",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
827,0500000US72127,"San Juan Municipio, Puerto Rico",121592,4257,100434,4423,89797,4570,10637,1866,...,221,705,423,7520,1399,3618,1168,1389,515,NaN
828,0500000US72135,"Toa Alta Municipio, Puerto Rico",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
829,0500000US72137,"Toa Baja Municipio, Puerto Rico",28333,2388,24517,2440,22265,2441,2252,718,...,221,0,221,253,236,1044,486,1362,740,NaN
830,0500000US72139,"Trujillo Alto Municipio, Puerto Rico",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [56]:
final_2015 = file_2015[['NAME', 'B08301_001E', 'B08301_021E', 'B08301_021M']]
final_2015.columns = ["Location", "Total_Workers", "Remote_Workers", "Margin_remote"]
final_2015 = final_2015.drop(index=0).reset_index(drop=True)

final_2016 = file_2016[['NAME', 'B08301_001E', 'B08301_021E', 'B08301_021M']]
final_2016.columns = ["Location", "Total_Workers", "Remote_Workers", "Margin_remote"]
final_2016 = final_2016.drop(index=0).reset_index(drop=True)

final_2017 = file_2017[['NAME', 'B08301_001E', 'B08301_021E', 'B08301_021M']]
final_2017.columns = ["Location", "Total_Workers", "Remote_Workers", "Margin_remote"]
final_2017 = final_2017.drop(index=0).reset_index(drop=True)

final_2018 = file_2018[['NAME', 'B08301_001E', 'B08301_021E', 'B08301_021M']]
final_2018.columns = ["Location", "Total_Workers", "Remote_Workers", "Margin_remote"]
final_2018 = final_2018.drop(index=0).reset_index(drop=True)

final_2019 = file_2019[['NAME', 'B08301_001E', 'B08301_021E', 'B08301_021M']]
final_2019.columns = ["Location", "Total_Workers", "Remote_Workers", "Margin_remote"]
final_2019 = final_2019.drop(index=0).reset_index(drop=True)

final_2021 = file_2021[['NAME', 'B08301_001E', 'B08301_021E', 'B08301_021M']]
final_2021.columns = ["Location", "Total_Workers", "Remote_Workers", "Margin_remote"]
final_2021 = final_2021.drop(index=0).reset_index(drop=True)

final_2022 = file_2022[['NAME', 'B08301_001E', 'B08301_021E', 'B08301_021M']]
final_2022.columns = ["Location", "Total_Workers", "Remote_Workers", "Margin_remote"]
final_2022 = final_2022.drop(index=0).reset_index(drop=True)

final_2023 = file_2023[['NAME', 'B08301_001E', 'B08301_021E', 'B08301_021M']]
final_2023.columns = ["Location", "Total_Workers", "Remote_Workers", "Margin_remote"]
final_2023 = final_2023.drop(index=0).reset_index(drop=True)

final_2024 = file_2024[['NAME', 'B08301_001E', 'B08301_021E', 'B08301_021M']]
final_2024.columns = ["Location", "Total_Workers", "Remote_Workers", "Margin_remote"]
final_2024 = final_2024.drop(index=0).reset_index(drop=True)

In [57]:
final_2015['year'] = 2015
final_2016['year'] = 2016
final_2017['year'] = 2017
final_2018['year'] = 2018
final_2019['year'] = 2019
final_2021['year'] = 2021
final_2022['year'] = 2022
final_2023['year'] = 2023
final_2024['year'] = 2024

In [58]:
df = pd.concat([final_2015, final_2016, final_2017, final_2018, final_2019, final_2021, final_2022, final_2023])

In [59]:
df

,Location,Total_Workers,Remote_Workers,Margin_remote,year
0,"Baldwin County, Alabama",NaN,NaN,NaN,2015
1,"Calhoun County, Alabama",NaN,NaN,NaN,2015
2,"Cullman County, Alabama",NaN,NaN,NaN,2015
3,"DeKalb County, Alabama",NaN,NaN,NaN,2015
4,"Elmore County, Alabama",NaN,NaN,NaN,2015
...,...,...,...,...,...
825,"Ponce Municipio, Puerto Rico",NaN,NaN,NaN,2023
826,"San Juan Municipio, Puerto Rico",121592,1389,515,2023
827,"Toa Alta Municipio, Puerto Rico",NaN,NaN,NaN,2023
828,"Toa Baja Municipio, Puerto Rico",28333,1362,740,2023
829,"Trujillo Alto Municipio, Puerto Rico",NaN,NaN,NaN,2023

In [60]:
house_price = pd.read_csv('County_zhvi_uc_sfrcondo_tier_0.33_0.67_sm_sa_month.csv')

In [61]:
house_price

,RegionID,SizeRank,RegionName,RegionType,StateName,State,Metro,StateCodeFIPS,MunicipalCodeFIPS,2000-01-31,...,2025-07-31,2025-08-31,2025-09-30,2025-10-31,2025-11-30,2025-12-31,2026-01-31,2026-02-28,2026-03-31,2026-04-30
0,3101,0,Los Angeles County,county,CA,CA,"Los Angeles-Long Beach-Anaheim, CA",6,37,213400.539313,...,881499.021276,881462.750505,883597.088761,886474.482410,889754.542617,893331.866133,895038.673823,895013.829173,893175.083769,890436.775426
1,139,1,Cook County,county,IL,IL,"Chicago-Naperville-Elgin, IL-IN-WI",17,31,151048.689270,...,318507.080729,319433.907158,320815.617773,322135.529845,323663.909643,325282.370266,326735.089367,328447.838017,330046.609986,331372.836300
2,1090,2,Harris County,county,TX,TX,"Houston-The Woodlands-Sugar Land, TX",48,201,113186.364199,...,285788.032100,285022.510893,284462.042110,284001.396373,283767.297770,283814.259320,283666.113614,283330.408884,282721.923873,282007.481538
3,2402,3,Maricopa County,county,AZ,AZ,"Phoenix-Mesa-Chandler, AZ",4,13,146879.546494,...,464990.520333,463310.654252,462223.146171,461788.590496,462013.791674,462802.800243,463660.716064,464337.890595,464183.468824,463173.388447
4,2841,4,San Diego County,county,CA,CA,"San Diego-Chula Vista-Carlsbad, CA",6,73,219424.890390,...,942695.345286,939198.024409,937301.040427,937268.802503,938290.071519,940494.202679,941741.880789,942776.141289,943160.847927,943046.645594
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3067,846,3206,Banner County,county,NE,NE,"Scottsbluff, NE",31,7,NaN,...,364404.110628,369197.829067,374020.219360,378030.606571,379633.257423,379723.424489,378420.932447,378260.734957,381724.374742,385049.008702
3068,1648,3207,Daggett County,county,UT,UT,NaN,49,9,NaN,...,344055.878271,347399.739662,352154.434457,355299.282473,358111.029876,359313.984582,360498.492539,362029.246018,363649.034418,364449.782542
3069,1432,3208,Thomas County,county,NE,NE,NaN,31,171,NaN,...,190271.074507,188249.064293,186781.692107,185969.482115,184030.206419,182320.676651,181274.934495,182960.959842,185184.125708,185683.374884
3070,2794,3212,McPherson County,county,NE,NE,"North Platte, NE",31,117,NaN,...,349521.850929,349876.295351,351830.692225,356163.987566,360587.169638,365143.456377,367207.436971,367064.788657,367260.846571,365554.785245
3071,2825,3214,Petroleum County,county,MT,MT,NaN,30,69,NaN,...,192517.011529,190187.853206,188061.376974,187574.355158,188889.784251,190409.198206,190997.961756,192021.410173,194058.881479,194992.975978

In [62]:
date_cols = [col for col in house_price.columns if col[:4].isdigit() and '-' in col]
meta_cols = ['RegionID', 'RegionName', 'StateName', 'State', 'Metro']

hp_long = house_price[meta_cols + date_cols].melt(id_vars=meta_cols, value_vars=date_cols, var_name='date', value_name='home_value')
hp_long['year'] = pd.to_datetime(hp_long['date']).dt.year
hp_avg = (hp_long.groupby(['RegionName', 'StateName', 'year'], as_index=False)['home_value'].mean().rename(columns={'home_value': 'avg_home_value'}).sort_values(['RegionName', 'year']))

print(hp_avg.head(20))

          RegionName StateName  year  avg_home_value
0   Abbeville County        SC  2000    57267.723359
1   Abbeville County        SC  2001    60099.143046
2   Abbeville County        SC  2002    64174.472103
3   Abbeville County        SC  2003    68381.796529
4   Abbeville County        SC  2004    71950.709199
5   Abbeville County        SC  2005    77346.302688
6   Abbeville County        SC  2006    83430.604430
7   Abbeville County        SC  2007    87571.203575
8   Abbeville County        SC  2008    89733.158027
9   Abbeville County        SC  2009    85377.488483
10  Abbeville County        SC  2010    80439.993546
11  Abbeville County        SC  2011    77799.133653
12  Abbeville County        SC  2012    80409.625533
13  Abbeville County        SC  2013    86732.064491
14  Abbeville County        SC  2014    90543.218992
15  Abbeville County        SC  2015   103447.222866
16  Abbeville County        SC  2016   115307.460888
17  Abbeville County        SC  2017   114583.993520
18  Abbeville County        SC  2018   121773.901111
19  Abbeville County        SC  2019   126903.306897

In [63]:
hp_avg

             RegionName StateName  year  avg_home_value
0      Abbeville County        SC  2000    57267.723359
1      Abbeville County        SC  2001    60099.143046
2      Abbeville County        SC  2002    64174.472103
3      Abbeville County        SC  2003    68381.796529
4      Abbeville County        SC  2004    71950.709199
...                 ...       ...   ...             ...
82939     Zavala County        TX  2022    95905.989682
82940     Zavala County        TX  2023    93497.321394
82941     Zavala County        TX  2024    87014.462032
82942     Zavala County        TX  2025    85418.003428
82943     Zavala County        TX  2026    91316.596250

[82944 rows x 4 columns]

In [64]:
state_abbrev = {
    'Alabama': 'AL', 'Alaska': 'AK', 'Arizona': 'AZ', 'Arkansas': 'AR',
    'California': 'CA', 'Colorado': 'CO', 'Connecticut': 'CT', 'Delaware': 'DE',
    'Florida': 'FL', 'Georgia': 'GA', 'Hawaii': 'HI', 'Idaho': 'ID',
    'Illinois': 'IL', 'Indiana': 'IN', 'Iowa': 'IA', 'Kansas': 'KS',
    'Kentucky': 'KY', 'Louisiana': 'LA', 'Maine': 'ME', 'Maryland': 'MD',
    'Massachusetts': 'MA', 'Michigan': 'MI', 'Minnesota': 'MN', 'Mississippi': 'MS',
    'Missouri': 'MO', 'Montana': 'MT', 'Nebraska': 'NE', 'Nevada': 'NV',
    'New Hampshire': 'NH', 'New Jersey': 'NJ', 'New Mexico': 'NM', 'New York': 'NY',
    'North Carolina': 'NC', 'North Dakota': 'ND', 'Ohio': 'OH', 'Oklahoma': 'OK',
    'Oregon': 'OR', 'Pennsylvania': 'PA', 'Rhode Island': 'RI', 'South Carolina': 'SC',
    'South Dakota': 'SD', 'Tennessee': 'TN', 'Texas': 'TX', 'Utah': 'UT',
    'Vermont': 'VT', 'Virginia': 'VA', 'Washington': 'WA', 'West Virginia': 'WV',
    'Wisconsin': 'WI', 'Wyoming': 'WY', 'District of Columbia': 'DC',
    'Puerto Rico': 'PR'
}
df[['county_name', 'state_full']] = (
    df['Location'].str.rsplit(',', n=1, expand=True).apply(lambda col: col.str.strip())
)

df['state_abbrev'] = df['state_full'].map(state_abbrev)
merged_df = pd.merge(df,hp_avg,left_on=['county_name', 'state_abbrev', 'year'],right_on=['RegionName', 'StateName', 'year'],how='left')

merged_df = merged_df.drop(columns=['county_name', 'state_full', 'RegionName', 'StateName'])

print(merged_df.shape)
print(merged_df.head())

(6640, 7)
                  Location Total_Workers Remote_Workers Margin_remote  year  \
0  Baldwin County, Alabama           NaN            NaN           NaN  2015
1  Calhoun County, Alabama           NaN            NaN           NaN  2015
2  Cullman County, Alabama           NaN            NaN           NaN  2015
3   DeKalb County, Alabama           NaN            NaN           NaN  2015
4   Elmore County, Alabama           NaN            NaN           NaN  2015

  state_abbrev  avg_home_value
0           AL   196608.088455
1           AL   114307.851676
2           AL   141466.859356
3           AL             NaN
4           AL   163824.289846

In [65]:
merged_df

,Location,Total_Workers,Remote_Workers,Margin_remote,year,state_abbrev,avg_home_value
0,"Baldwin County, Alabama",NaN,NaN,NaN,2015,AL,196608.088455
1,"Calhoun County, Alabama",NaN,NaN,NaN,2015,AL,114307.851676
2,"Cullman County, Alabama",NaN,NaN,NaN,2015,AL,141466.859356
3,"DeKalb County, Alabama",NaN,NaN,NaN,2015,AL,NaN
4,"Elmore County, Alabama",NaN,NaN,NaN,2015,AL,163824.289846
...,...,...,...,...,...,...,...
6635,"Ponce Municipio, Puerto Rico",NaN,NaN,NaN,2023,PR,NaN
6636,"San Juan Municipio, Puerto Rico",121592,1389,515,2023,PR,NaN
6637,"Toa Alta Municipio, Puerto Rico",NaN,NaN,NaN,2023,PR,NaN
6638,"Toa Baja Municipio, Puerto Rico",28333,1362,740,2023,PR,NaN
6639,"Trujillo Alto Municipio, Puerto Rico",NaN,NaN,NaN,2023,PR,NaN

In [66]:
merged_df.dropna().shape[0]

print(f"Total rows:         {len(merged_df)}")
print(f"Complete rows:      {merged_df.dropna().shape[0]}")
print(f"Rows with any NaN:  {merged_df.isna().any(axis=1).sum()}")
print(merged_df.isna().sum())

Total rows:         6640
Complete rows:      2967
Rows with any NaN:  3673
Location             0
Total_Workers     3488
Remote_Workers    3488
Margin_remote     3488
year                 0
state_abbrev         0
avg_home_value     388
dtype: int64

In [67]:
clean_df = merged_df.dropna().reset_index()

In [68]:
clean_df

,index,Location,Total_Workers,Remote_Workers,Margin_remote,year,state_abbrev,avg_home_value
0,6,"Houston County, Alabama",42914,1256,429,2015,AL,121614.660639
1,7,"Jefferson County, Alabama",301226,8690,1506,2015,AL,123677.326674
2,11,"Madison County, Alabama",162142,4193,1089,2015,AL,168982.798635
3,13,"Mobile County, Alabama",171912,7466,1832,2015,AL,110000.375372
4,25,"Cochise County, Arizona",43051,1929,559,2015,AZ,151200.749692
...,...,...,...,...,...,...,...,...
2962,6619,"Rock County, Wisconsin",77303,2145,505,2023,WI,241105.396373
2963,6621,"Sheboygan County, Wisconsin",58443,1841,502,2023,WI,261370.178191
2964,6623,"Washington County, Wisconsin",72794,2006,509,2023,WI,361907.038122
2965,6624,"Waukesha County, Wisconsin",210053,7722,1213,2023,WI,432671.566863
2966,6625,"Winnebago County, Wisconsin",85337,2598,638,2023,WI,255416.247676